semaphore/semaphore/core/management/forms.py
from pymongo.objectid import ObjectId
from flaskext.wtf import Form, HiddenField, Required, SubmitField, TextField, \
		TextAreaField, SelectField, Length, Email, PasswordField

__all__ = ["ProductForm", "OrganizationForm","UserForm", "UserForm2"]

def coerceBool(x):
	if type(x) == bool:
		return str(x)
	elif type(x) == str or type(x) == unicode:
		return x.lower() == 'true'
	else:
		return x

class UserForm(Form):
	uid = HiddenField('uid')
	name = TextField('User Email', validators=[Email(message='Invalid email address.')])
	password = PasswordField('Password', validators=[Length(min=1,max=64, message='Invalid Password')])
	active = SelectField('Active', choices =[(True, 'Active'),(False, 'Inactive')], 
			coerce=bool, default=True)
	submit = SubmitField('Submit')
	
class UserForm2(Form):
	uid = HiddenField('uid')
	name = TextField('Full Name', validators=[Length(min=1,max=64,message='Invalid Full Name')])
	username = TextField('User Email', validators=[Email(message='Invalid email address.')])
	password = PasswordField('Password', validators=[Length(min=1,max=64, message='Invalid Password')])
	active = SelectField('Active', choices =[(True, 'Active'),(False, 'Inactive')], 
			coerce=bool, default=True)
	submit = SubmitField('Submit')

class OrganizationForm(Form):
	name = TextField('Organization Name', 
			validators=[Length(min=1,max=64, message='Invalid Name')])
	active = SelectField('Active', choices =[(True, 'Active'),(False, 'Inactive')], 
			coerce=bool, default=True)
	submit = SubmitField('Make Changes')


class ProductForm(Form):
	pid = HiddenField('pid')
	name = TextField('Title', validators=[Length(min=1,max=64, message='Invalid Name')])
	submit = SubmitField('Submit')
	active = SelectField('Active', choices =[(True, 'Active'),(False, 'Inactive')], 
			coerce=coerceBool, default=True)

semaphore/semaphore/core/management/__init__.py
from flask import Blueprint, flash, g, redirect
from flask import request, session, url_for, current_app as app


module = Blueprint('management', __name__, template_folder="../../templates")

from .views import *

semaphore/semaphore/core/management/views.py
from flask import current_app as app, g, render_template, redirect, url_for, \
		request

from semaphore.core.auth.decorators import login_required
from semaphore.core.settings.decorators import permission_required

from semaphore.core.settings import permissions

from semaphore.core.auth.models import User
from semaphore.core.tickets.models import Product

from . import module
from .forms import *

__all__ = ["index", "user_browse", "user_add","product_create","product_edit","user_edit","products_browse","organization_save"]

@module.route("/manage")
@permission_required(permissions.ORGANIZATION, permissions.MANAGE)
@login_required
def index():
	return render_template('management/index.html')


@module.route("/manage/users")
@login_required
@permission_required(permissions.USERS, permissions.READ)
def user_browse():
	form = UserForm(request.form)
	users = User.get_all_users(g.organization._id)
	return render_template('management/users/browse_users.html', users=users, form=form)
	
	
@module.route("/manage/users/create")
@login_required
@permission_required(permissions.USERS, permissions.CREATE)
def user_create():
	form = UserForm2(request.form)
	return render_template('management/users/create_users.html', form=form)	

@module.route("/user/profile/edit")
@login_required
def edit_profile():
	user = User.get_user_id(g.user._id)
	if user is None:
		redirect(url_for('dashboard.index'))
	form = UserForm(request.form)
	form.populate_obj(user)
	return render_template('management/users/profile_edit.html', form=form)
	
@module.route("/user/profile/view")
@login_required
def view_profile():
	user = User.get_user_id(g.user._id)
	if user is None:
		redirect(url_for('dashboard.index'))

	return render_template('management/users/view_profile.html', user=user)
	
	
		

@module.route("/manage/users/save",  methods=('GET','POST'))
@login_required
@permission_required(permissions.USERS, permissions.CREATE)
def user_save(methods=('GET','POST')):
	form = UserForm2(request.form)
	if form.validate():
		if len(form.uid.data) > 0:
			# Existing user
			user = User.get_user_id(form.uid.data)
		else:
			# New user
			user = User()
			user.organization = g.organization
			user.active = form.active.data
			user.username = form.name.data
			user.name.first, user.name.last = form.name.data.split(' ')
			user.password = Password().set_password(form.password.data)
		user.save()
		return redirect(url_for('management.user_browse'))
	else:
		print "WTF?!"
		print form.errors
		return render_template('management/users/edit_users.html',
				form=form)
	
	
	
	return render_template('management/products/create_users.html', form=form)	
	
	
@module.route("/manage/users/add", methods=('POST',))
@login_required
@permission_required(permissions.USERS, permissions.CREATE)
def user_add():
	# Find the username given
	user = User.get_user(request.form['name'])
	if user is None:
		flash(_("<strong>The user you tried to create does not exist.</strong>\
		Please check the username and try again."))
		return redirect(url_for('manage.user_browse'))

	user.organizations.append(g.organization)
	user.save()

	return redirect(url_for('management.user_browse'))

@module.route('/manage/users/edit/<id>', methods=('GET','POST'))
@login_required
@permission_required(permissions.USERS, permissions.MODIFY)
def user_edit(id, methods=('GET','POST')):
	user = User.get_user_id(id)
	print user
	form = EditUserForm(request.form, user)
	form.uid.data = id; 
	form.populate_obj(user)
	if request.method == 'POST' and form.validate_on_submit():
		user.active = form.active.data
		name = form.name.data
		name_split = name.split(" ")
		user.name = create_name(name_split[0], name_split[1])
		if form.password is not None:
			user.password = set_password(form.password.data)
		user.save()
		
	return render_template('management/users/edit_users.html', form=form)
	

@module.route('/manage/products')
@login_required
@permission_required(permissions.PRODUCTS, permissions.READ)
def products_browse():
	products = Product.get_all_products(g.organization._id)
	return render_template('management/products/browse_products.html', products=products)
	

@module.route('/manage/products/create')
@login_required
@permission_required(permissions.PRODUCTS, permissions.CREATE)
def product_create():
	form = ProductForm(request.form)
	return render_template('management/products/create_product.html', form=form)

@module.route('/manage/products/edit/<id>')
@login_required
@permission_required(permissions.PRODUCTS, permissions.MODIFY)
def product_edit(id):
	form = ProductForm(request.form, Product.get_product(id))
	form.pid.data = id
	return render_template('management/products/edit_product.html', form=form)

@module.route('/manage/products/save', methods=('POST',))
@login_required
@permission_required(permissions.PRODUCTS, permissions.MODIFY)
def product_save():
	form = ProductForm(request.form)
	if form.validate():
		if len(form.pid.data) > 0:
			# Existing product
			product = Product.get_product(form.pid.data)
		else:
			# New product
			product = Product()
			product.organization = g.organization
			product.active = True
	
		form.populate_obj(product)
		product.save()
		return redirect(url_for('management.products_browse'))
	else:
		print "WTF?!"
		print form.errors
		return render_template('management/products/edit_product.html',
				form=form)

@module.route('/manage/organization/save', methods=('POST',))
@login_required
@permission_required(permissions.ORGANIZATION, permissions.MODIFY)
def organization_save():
	form = OrganizationForm(request.form)
	if form.validate():
		form.populate_obj(g.organization)
		g.organization.save()
	else:
		print form.errors
		return render_template('management/organizations/edit_organization.html',
				form=form);
	return redirect(url_for('dashboard.index'))

@module.route('/manage/organization/edit', methods=('GET','POST'))
@login_required
@permission_required(permissions.ORGANIZATION, permissions.MODIFY)
def organization_edit():
	form = OrganizationForm(request.form, g.organization)
	return render_template('management/organizations/edit_organization.html', form=form)

semaphore/semaphore/templates/management/users/browse_users.html
{% extends "management/base.html" %}

{% block title %}Browse Users{% endblock %}
{% block management_content %}
	<table class="table table-striped">
		<thead> 
			<tr>
				<th>Username</th>
				<th>Name</th>
				<th>Actions</th>
			</tr>
		</thead>
		<tbody>
			{% for user in users %}
				<tr>
					<td>{{ user.username }}</td>
					<td>{{ user.name|display_name }}</td>
					<td>
						
						<!--| <a href="#">Manage Permissions</a>-->
					</td>
				</tr>
			{% endfor %}
		</tbody>
	</table>
	
	<form method="POST" action="{{url_for('management.user_add')}}" class="zeropad form-horizontal" _lpchecked="1">
          {{ forms.form_fields([form.csrf, form.name], ignore_required='true', legend="Append User to Organization") }}
        {{ forms.action_buttons("Create", size="large") }}
    </form>
    <hr>
	
	<a href="{{url_for('management.user_create')}}">Add User</a>
{% endblock %}

semaphore/semaphore/templates/management/users/create_users.html
{% extends "dashboard/dashboard_base.html" %}

{% block title %} {{ g.organization.name }} - Create User {% endblock %}

{% block dash_content %}
	<div class="span10">
		<div class="offset2">
    <form method="POST" action="{{url_for('management.user_save')}}" class="zeropad form-horizontal" _lpchecked="1">
          {{ forms.form_fields([form.csrf, form.name, form.username, form.password], ignore_required='true', legend="Create User") }}
        {{ forms.action_buttons("Create", size="large") }}
    </form>
    	</div>
    </div>
{% endblock %}

semaphore/semaphore/templates/management/users/edit_users.html
{% extends "dashboard/dashboard_base.html" %}

{% block title %} {{ g.organization.name }} - Edit User {% endblock %}

{% block dash_content %}
	<div class="span10">
		<div class="offset2">
    <form method="POST" action="{{url_for('auth.edit', id=id) }}" class="zeropad form-horizontal" _lpchecked="1">
        {{ forms.form_fields([form.f_name, form.l_name, form.password, form.active], ignore_required='true', legend="Edit User") }}
        {{ forms.action_buttons("Submit Changes", size="large") }}
    </form>
    	</div>
    </div>
{% endblock %}

semaphore/semaphore/templates/management/users/profile_edit.html
{% extends "dashboard/dashboard_base.html" %}

{% block title %} {{ g.organization.name }} - User Profile - {{ session.username }} {% endblock %}

{% block dash_content %}
	<div class="span10">
		<div class="offset2">
    <form method="POST" action="{{url_for('management.edit_profile')}}" class="zeropad form-horizontal" _lpchecked="1">
        {{ forms.form_fields([form.name, form.password], ignore_required='true', legend="Your Profile") }}
        {{ forms.action_buttons("Submit Changes", size="large") }}
    </form>
    	</div>
    </div>
{% endblock %}

semaphore/semaphore/templates/management/users/view_profile.html
{% extends 'dashboard/dashboard_base.html' %}
{% block title %}{{ g.organization.name }} - Viewing User{% endblock %}
{% block dash_content %}
   
    <div class="span12">
    	 
		<div class="offset2">
			<h2>Viewing Profile :  {{ g.user.name.first}} {{ g.user.name.last }}</h2> <!-- Keep for testing-->
			<div class="well">
    			  
					    		<b>Email: </b>
					    			    		
					    		<a href="mailto:{{ g.user.username }}"> {{ g.user.username }} </a>
					    		
					    <br><br>
						<!--					    <a href="#">Edit Profile</a>-->
    		</div>
    	</div>
    </div>
{% endblock %}