semaphore/semaphore/core/tickets/models.py
import datetime
from flask import current_app as app
from flaskext.mongoengine import Document

from pymongo.objectid import ObjectId
from mongoengine import EmbeddedDocument
from mongoengine import StringField, ReferenceField, BooleanField,\
		DateTimeField, EmbeddedDocumentField, FileField, ListField,\
		DictField, IntField, signals
from mongoengine.base import BaseList

from semaphore.core.auth.models import User
from semaphore.core.organizations.models import Organization
import config

STATUSES = ["New", "Opened", "Assigned", "Reopened", "Closed", "Pending",\
		"WONT FIX"]
PRIORITIES = ["Undetermined", "Trivial", "Minor", "Major", "Critical",\
		"Blocker"]

class Product(Document):
	"""
	Represents a product/project in Semaphore
	"""
	name = StringField(required=True)
	organization = ReferenceField(Organization, required=True)
	active = BooleanField(required=True)

	def __repr__(self):
		return '<Product:' + str([str(x) + ':' + str(getattr(self,x)) for x in
				self._fields]) + '>'
	
	def __str__(self):
		return self.__repr__()
	
	@classmethod
	def get_product(cls, product_id):
		"""
		Returns a product with a given ID that's active.
		"""
		return cls.objects(__raw__={'_id': ObjectId(product_id), 'active':
			True}).first()

	@classmethod
	def get_all_products(cls, org_id):
		return cls.objects(__raw__={'organization.$id':ObjectId(org_id), 'active': True})


class Comment(EmbeddedDocument):
	"""
	A comment on a ticket from a user
	"""

	def __hash__(self):
		return self.owner.__hash__() * (31 * self.body.__hash__()) * (31 *
				self.timestamp.__hash__())

	def __eq__(self, other):
		return self.__hash__() == other.__hash__()

	owner = ReferenceField(User, required=True)
	timestamp = DateTimeField(required=True, default=datetime.datetime.utcnow)
	body = StringField(required=True)
	active = BooleanField(required=True, default=True)

	def __repr__(self):
		return '<Comment:' + str([str(x) + ':' + str(getattr(self,x)) for x in
				self._fields]) + '>'

	def __str__(self):
		return self.__repr__()


class Changeset(EmbeddedDocument):
	"""
	A set of changes on a ticket
	"""
	owner = ReferenceField(User, required=True)
	timestamp = DateTimeField(required=True, default=datetime.datetime.utcnow)
	types = ListField(StringField())
	involves = ListField(ReferenceField(User))
	fields = DictField()

	def __repr__(self):
		return '<Changeset:' + str([str(x) + ':' + str(getattr(self,x)) for x in
				self._fields]) + '>'
	
	def __str__(self):
		return self.__repr__()

class Attachment(EmbeddedDocument):
	"""
	An attachment (file) on a ticket
	"""
	
	def __hash__(self):
		return self.owner.__hash__() * (31 * self.title.__hash__())
	
	owner = ReferenceField(User, required=True)
	files = ListField(FileField())
	title = StringField()


class Ticket(Document):
	"""
	Represents a ticket in Semaphore
	"""
	organization = ReferenceField(Organization, required=True)
	active = BooleanField(required=True, default=True)
	owner = ReferenceField(User, required=True)
	title = StringField(required=True)
	title_keywords = ListField(StringField())
	body = StringField()
	priority = IntField()
	status = IntField()
	tags = ListField(StringField())
	product = ReferenceField(Product, required=True)
	dynamic_fields = DictField()

	last_modified = DateTimeField(required=True,
			default=datetime.datetime.utcnow)

	comments = ListField(EmbeddedDocumentField(Comment))
	attachments = ListField(EmbeddedDocumentField(Attachment))
	changesets = ListField(EmbeddedDocumentField(Changeset))
	watchers = ListField(User)

	UNDIFFABLE_FIELDS = [changesets, title_keywords]

	@classmethod
	def handle_migrations(cls, sender, document, **kwargs):
		"""
		Handles running any migration hooks.
		"""
		#if document.id:
			#if (len(document.title_keywords) == 0 and len(document.title) > 0):
				#print "Migrating ticket %s" % document.id
				#document.title_keywords.extend(document.title.lower().split())
				#document.save()
			#elif len(document.title_keywords) > 0:
				#document.title_keywords = [x.lower() for x in
						#document.title_keywords]
				#document.save()
		pass

	def __repr__(self):
		return '<Ticket:' + str([str(x) + ':' + str(getattr(self,x)) for x in
				self._fields]) + '>'
	
	def __str__(self):
		return self.__repr__()

	@classmethod
	def pre_save(cls, sender, document, **kwargs):
		"""
		Handles creating a changeset and updating title_keywords
		"""
		document.title_keywords = document.title.lower().split(" ")

		# Build a new changeset
		if len(document._delta()) > 0 and document.save_owner:
			changeset = Changeset(owner=document.save_owner)
			fields = document._delta()[0]
		
			# Get the old ticket so we can diff collections
			old_ticket = Ticket.get_ticket(document.id)

			for field in fields.keys():
				if field not in document._fields or field in document.UNDIFFABLE_FIELDS:
					pass
				elif isinstance(getattr(document, field), (BaseList,)):
					# TODO: Diff the collection
					if old_ticket is None:
						changeset.fields[field] = (getattr(document, field), [])
					else:
						added = set(getattr(document,
							field)) - (set(getattr(old_ticket, field)))
						removed = set(getattr(old_ticket, field)) -\
								set(getattr(document, field))
						if len(added) > 0 or len(removed) > 0:
							changeset.fields[field] = (list(added), list(removed))
							changeset.types.append(field)
				else:
					# Just add the field
					if old_ticket is None:
						changeset.fields[field] = (getattr(document, field),
								None)
					else:
						v = getattr(old_ticket, field)
						nv = getattr(document, field)
						if v != nv:
							changeset.fields[field] = (getattr(document, field),
									getattr(old_ticket, field))
							changeset.types.append(field)

			if old_ticket is None:
				changeset.types = ['new',]

			changeset.involves = list(set(document.watchers +
				[document.save_owner, document.owner]))

			if len(changeset.types) > 0:
				document.changesets.append(changeset)
				# Update last modified 
				document.last_modified = datetime.datetime.utcnow()


	@classmethod
	def get_ticket(cls, ticket_id):
		"""
		Finds a ticket in the database.
		"""
		return cls.objects(__raw__={"_id": ObjectId(ticket_id), "active":
			True}).first()

	@classmethod
	def get_tickets_of_org(cls, org_id):
		"""
		Gets all active tickets of an organization ; filter by user if specified
		"""
		return cls.objects(__raw__={"organization.$id": ObjectId(org_id),
			"active": True}).order_by('-last_modified')
	
	@classmethod
	def get_tickets_involving(cls, org_id , user):
		"""
		Gets all active tickets an user is involved in 
		"""
		return cls.objects(__raw__ ={"organization.$id": ObjectId(org_id), 
			"changesets.involves.$id": user.id,
			"active": True}).order_by('-last_modified')
	
	@classmethod
	def search_tickets(cls, org_id, terms):
		"""
		Searches for a ticket that has some of the terms
		"""
		results = set()
		for term in terms:
			results.update(set(cls.objects(__raw__={"organization.$id":
				ObjectId(org_id), "active": True, "tags":
				term.lower()})));
			results.update(set(cls.objects(__raw__={"organization.$id":
				ObjectId(org_id), "active": True, "title_keywords":
				term.lower()})));
		return results;

	@classmethod
	def search_by_tag(cls, org_id, tag):
		return cls.objects(__raw__={'organization.$id': ObjectId(org_id),
			'tags': tag, 'active': True})

	def add_comment(self, owner, body):
		"""
		Adds a comment to the ticket
		"""
		comment = Comment(owner=owner, body=body)
		self.comments.append(comment)

	## HACK HACK HACK HACK HACK
	## God murders kittens every time this function is called
	def save(self, *args, **kwargs):
		self.save_owner = kwargs['owner'] if 'owner' in kwargs else None
		if 'owner' in kwargs: del kwargs['owner']
		r = super(Ticket, self).save(*args, **kwargs)
		self.kwargs = {}
		return r

signals.pre_save.connect(Ticket.pre_save, sender=Ticket)
signals.post_init.connect(Ticket.handle_migrations, sender=Ticket)

semaphore/semaphore/core/tickets/forms.py
import string

from pymongo.objectid import ObjectId
from flask.ext.mongoengine import Document
from wtforms import widgets, ValidationError
from flaskext.wtf import Form, HiddenField, SubmitField, TextField, \
		TextAreaField, SelectField

from flaskext.wtf import Required, Length

from semaphore.core.tickets.models import Product, Ticket, PRIORITIES, STATUSES
from semaphore.core.auth.models import User

# Inspired by bitbucket.org/maratfm/wtforms/
class QSSelectField(SelectField):
	widget = widgets.Select()
	def __init__(self, label=u'', validators=None, queryset=None,
			label_attr=u'', allow_blank=False, blank_text=u'---',
			none_value=u'__None', **kwargs):
		super(QSSelectField, self).__init__(label, validators, **kwargs)
		self.label_attr = label_attr
		self.allow_blank = allow_blank
		self.blank_text = blank_text
		self.none_value = none_value
		self.queryset = queryset or []

	def iter_choices(self):
		if self.allow_blank:
			yield(self.none_value, self.blank_text, self.data is None)

		if not self.queryset:
			return

		self.queryset.rewind()
		for q in self.queryset:
			if not self.label_attr:
				label = unicode(q)
			else:
				if hasattr(self.label_attr, '__iter__'):
					def get_complexattr(q, x):
						o = q
						for seg in x.split('.'):
							o = getattr(o, seg)
						return o

					label = " ".join([get_complexattr(q, x) for x in self.label_attr])
				else:
					label = getattr(q, self.label_attr)
			c = (q.id == self.data.id) if hasattr(self.data, 'id') else unicode(q.id) == unicode(self.data)
			yield (q.id, label, c)

	def process_formdata(self, valuelist):
		self.data = None
		if valuelist:
			print valuelist
			if (self.allow_blank and valuelist[0] == self.none_value) or not self.queryset:
				pass
			else:
				q = self.queryset.clone()
				q.filter(id=ObjectId(valuelist[0]))
				self.data = q.first()

	def process_data(self, value):
		print type(value)
		if hasattr(value, 'id'):
			self.data = unicode(value.id)
		else:
			self.data = unicode(value)

		return self.data

	def filter_id(self, id):
		return filter(lambda x: x in string.hexdigits, id)

	def pre_validate(self, form):
		q = self.queryset.clone()
		if len(self.raw_data) > 0:
			key = self.filter_id(self.raw_data[0])
			if len(key) == 24:
				if q.filter(id=ObjectId(key)).count() == 0:
					raise ValidationError('Not a valid choice')
			else:
				raise ValidationError('Invalid Object ID')
		else:
			raise ValidationError('Invalid Object ID')


class TagsField(TextField):
	"""
	A field that automatically splits items based on a delimiter
	"""

	widget = widgets.TextInput()
	
	def process_formdata(self, valuelist):
		self.data = []
		if len(valuelist) > 0:
			self.data = filter(lambda x: len(x) > 0, [x.strip() for x in
				valuelist[0].strip().split(",")])
	
	def process_data(self, value):
		self.data = u",".join(value) if value else u''

class TicketForm(Form):

	def bind_runtime_fields(self, g, ticket=None):
		self.product.queryset = Product.get_all_products(g.organization._id)
		self.owner.queryset = User.get_all_users(g.organization._id)
		if ticket is not None:
			self.tid.data = ticket.id
		else:
			self.owner.default = unicode(g.user.id)

	tid = HiddenField('id', validators=[Length(max=24)])
	title = TextField('Title')
	body = TextAreaField('Body')
	priority = SelectField('Priority', choices=[(x, PRIORITIES[x]) for x in\
		xrange(len(PRIORITIES))], coerce=int)
	product = QSSelectField('Product', label_attr='name')
	tags = TagsField('Tags', description='Comma separated (e.g., auth,crash,login)')
	owner = QSSelectField('Owner', label_attr=('name.first', 'name.last'))
	new_comment = TextAreaField('Comment')
	status = SelectField('Status', choices=[(x, STATUSES[x]) for x in
		xrange(len(STATUSES))], coerce=int, default=0)
	submit = SubmitField('Submit')

semaphore/semaphore/core/dashboard/__init__.py
from flask import Blueprint

__all__ = ["module"]

module = Blueprint('dashboard', __name__, template_folder="../../templates")

from .views import *

semaphore/semaphore/core/dashboard/views.py
from flask import render_template, url_for, request, g

from semaphore.core.auth.decorators import login_required

from . import module
from semaphore.core.tickets.models import Ticket

@module.route('/', methods=('GET',))
@login_required
def index():
	# Create a list of tiles...
	tickets = Ticket.get_tickets_of_org(g.organization._id).limit(5)
	my_tickets = Ticket.get_tickets_involving(g.organization._id, g.user).limit(5)
	return render_template('dashboard/dashboard_home.html', tickets=tickets , my_tickets=my_tickets)

semaphore/semaphore/core/tickets/__init__.py
from flask import Blueprint, flash, g, redirect
from flask import request, session, url_for, current_app as app


module = Blueprint('tickets', __name__, template_folder="../../templates")

from .views import *
from . import models

semaphore/semaphore/core/tickets/views.py
import datetime
from pymongo.objectid import ObjectId
from flask import Module, render_template, url_for, request, session, redirect
from flask import flash, current_app as app, abort, g

from semaphore.core.auth.decorators import login_required
from semaphore.core.settings.decorators import permission_required
from semaphore.core.settings.permissions import resolve_permission

from semaphore.core.settings import permissions

from . import module
from .models import Ticket
from .forms import TicketForm

@module.route('/ticket/<id>', methods=('GET', 'POST'))
@login_required
@permission_required(permissions.TICKET, permissions.READ)
def view(id):
	# Check that the ticket requested belongs to the organization
	# that the user belongs to.
	ticket = Ticket.get_ticket(id)
	if ticket is None:
		abort(404)

	form = TicketForm(request.form, ticket)
	form.bind_runtime_fields(g, ticket)
	
	if request.method == 'POST' and form.validate_on_submit():
		# Check for the permission
		if resolve_permission(permissions.TICKET, permissions.MODIFY):
			# DO SOMETHING
			pass
		elif resolve_permission(permissions.COMMENT, permissions.CREATE):
			# They only have the permission to add a comment, so just add their
			# comment. 
			ticket.add_comment(g.user, form.body.data)
		else:
			flash(_('You do not have permission to modify tickets'))
		return redirect(url_for('tickets.view', id=id))

	return render_template('tickets/ticket_view.html', form=form,
			ticket=ticket, modifable=resolve_permission(permissions.TICKET,
				permissions.MODIFY),
			commentable=resolve_permission(permissions.COMMENT,
				permissions.CREATE))


@module.route('/ticket/search')
@login_required
@permission_required(permissions.TICKET, permissions.READ)
def search():
	q = request.args.get('q', '')
	results = Ticket.search_tickets(g.organization._id,
			q.split(" "))
	return render_template('tickets/search_tickets.html', tickets=results, q=q)

@module.route('/ticket/tags/<tag>')
@login_required
@permission_required(permissions.TICKET, permissions.READ)
def tag_view(tag):
	results = Ticket.search_by_tag(g.organization._id, tag)
	return render_template('tickets/search_tickets.html', tickets=results,
			q=tag)

@module.route('/ticket/browse')
@login_required
@permission_required(permissions.TICKET, permissions.READ)
def browse():
	tickets = Ticket.get_tickets_of_org(g.organization._id)
	return render_template('tickets/browse_tickets.html', tickets=tickets)


@module.route('/ticket/create', methods=('GET','POST'))
@login_required
@permission_required(permissions.TICKET, permissions.CREATE)
def create():
	form = TicketForm(request.form)
	# Bind the product options to the form
	form.bind_runtime_fields(g)
	return render_template('tickets/create_ticket.html', form=form)


@module.route('/ticket/delete/<id>')
@login_required
@permission_required(permissions.TICKET, permissions.DELETE)
def delete(id):
	ticket = Ticket.get_ticket(id)
	if ticket is not None:
		ticket.active = False
		ticket.save()

	return redirect(url_for('tickets.browse'))

@module.route('/ticket/save', methods=('POST',))
@login_required
def save():
	# Bind the ticket form and validate
	form = TicketForm()
	form.bind_runtime_fields(g)
	form.process(request.form)

	print form.tid.data
	
	if form.validate():
		print form.tid.data
		if form.tid.data is not u"":
			# Modified ticket, grab the original ticket and check that we can
			# modify it
			ticket = Ticket.get_ticket(form.tid.data)
			if ticket.organization in g.user.organizations\
					and resolve_permission(permissions.TICKET,
							permissions.MODIFY):
				pass
			else:
				flash(_("You do not have permission to modify tickets."))
				return redirect(url_for('dashboard.index'))
		else:
			ticket = Ticket()
			ticket.status = 0
			ticket.organization = g.organization
			# New ticket. Check permissions
			if not resolve_permission(permissions.TICKET, permissions.CREATE):
				flash(_("You do not have permission to create new tickets."))
				return redirect(url_for('dashboard.index'))

		# Populate the ticket object
		form.populate_obj(ticket)
		# Populate the comments (since it isn't populated by populate_obj)
		if len(form.new_comment.data) > 0:
			ticket.add_comment(g.user, form.new_comment.data)
		
		# Save!
		ticket.save(owner=g.user)
		# Redirect to new/saved ticket
		return redirect(url_for('tickets.view', id=ticket.id))
	else:
		if len(form.tid.raw_data) == 0 or form.tid.raw_data[0] == u'':
			return render_template('tickets/create_ticket.html', form=form)
		else:
			return render_template('tickets/ticket_view.html', form=form,
					ticket=Ticket.get_ticket(form.tid.raw_data[0]))

semaphore/semaphore/templates/dashboard/dashboard.html
{% extends 'dashboard/dashboard_base.html' %}

semaphore/semaphore/templates/dashboard/dashboard_base.html
{% extends 'base.html' %}

{% block pre_content_area %}
	<div class="navbar">
		<div class="navbar-inner">
			<div class="container" style="width: auto;">
				<a class="brand" href="{{ url_for('dashboard.index') }}">
					{{ g.organization.name }}
				</a>
				<ul class="nav">
					<li class="dropdown">
					<a href="#" class="dropdown-toggle" data-toggle="dropdown">
						<i class="icon-flag icon-white"></i>
						Tickets
						<b class="caret"></b>
					</a>
					<ul class="dropdown-menu">
						<li><a href="{{ url_for('tickets.create') }}">
							<i class="icon-plus-sign"></i>New Ticket
						</a></li>
						<li><a href="{{ url_for('tickets.browse') }}">
							<i class="icon-chevron-right"></i>Browse Tickets
						</a></li>
					</ul>
					</li>
				</ul>

				<form class="navbar-search" method="GET" action="{{
					url_for('tickets.search') }}">
					<input type="text" name="q" id="q" class="search-query" placeholder="Search" />
				</form>
				<ul class="nav pull-right">
					<li class="dropdown pull-right">
					<a href="#" class="dropdown-toggle" data-toggle="dropdown">
						<i class="icon-user icon-white"></i>
						{{ g.user.name|display_name }}
						<b class="caret"></b>
					</a> 
					<ul class="dropdown-menu">
						<li><a href="{{url_for('management.view_profile')}}"><i class="icon-cog"></i>Your Profile</a></li>
						<li><a href="{{url_for('management.index')}}"><i class="icon-flag"></i>Manage</a></li>
						{% if g.user.active_organizations | count > 1 %}
							<li class="divider"></li>
							{% for org in g.user.active_organizations %}
								<li>
									<a href="{{ url_for('auth.change_organization', id=org._id) }}">
										{{ org.name }}
									</a>
								</li>
							{% endfor %}
						{% endif %}
						<li class="divider"></li>
						<li><a href="{{ url_for('auth.logout') }}">
							<i class="icon-off"></i>
							Logout
						</a></li>
					</ul>
					</li>
				</ul>
			</div>
		</div>
	</div>
{% endblock %}
{% block content %}
	<div class="content">
		{% block dash_content %}
		{% endblock %}
	</div>
{% endblock %}

semaphore/semaphore/templates/dashboard/dashboard_home.html
{% extends "dashboard/dashboard_base.html" %}
 
{% block title %} Dashboard Home {% endblock %}

{% block dash_content %} 

<div class="row">

 <div class="span6">
                    <div class ="well">
                    		<h2> Recent Activity</h2>
                    		<table class="table table-striped">
                <thead> 
                    <tr>
                        <th> Ticket Title </th>
                        <th> Last Updated</th>
                        <th> Status </th>
                    </tr>
                </thead>
                <tbody>
                    {% for ticket in tickets %}
                    	
                            <tr>
                                <td><a href="{{ url_for('tickets.view',
										id=ticket._id)}}">
										{{ ticket.title }}
								</a></td>
								<td>
                                	{{ ticket.last_modified|timestamp_format }}
                            	 </td>
                             

                                <td> <span class="label label-important"> {{
                                        ticket.status|readable_status }} </span> </td>
                               
                            </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
    
    
    

 <div class="span6">
                    <div class ="well">
                    		<h2> Your Tickets</h2>
                    		<table class="table table-striped">
                <thead> 
                    <tr>
                        <th> Ticket Title </th>
                        <th> Last Updated</th>
                        <th> Status </th>
                    </tr>
                </thead>
                <tbody>
                    {% for ticket in my_tickets %}
                    	
                            <tr>
                                <td><a href="{{ url_for('tickets.view',
										id=ticket._id)}}">
										{{ ticket.title }}
								</a></td>
								<td>
                                	{{ ticket.last_modified|timestamp_format }}
                            	 </td>
                             

                                <td> <span class="label label-important"> {{
                                        ticket.status|readable_status }} </span> </td>
                               
                            </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>    
    
    
    
    
</div>
{% endblock %}

semaphore/semaphore/templates/dashboard/ticket_utils.html
{%- macro ticket_description(ticket) -%}
<h1></h1><br>
<div class ="row-fluid">
	<div class ="well">
		<table>
			<h1> {{ticket.title}} </h1>
			<tr>
				<th>Priority: </th>
				<td> <span class="label important"> {{ticket.priority}} </span> </td>

				<th>Tags: </th>
				<td> {% for tag in ticket.tags %}<span class="label"> {{tag}} </span> {% endfor%}</td>


			</tr>

			<tr>
				<th>Status: </th>
				<td> 
					<span class="label warning">
						{{ ticket.status_readable }}
					</span>
				</td>
				<th>Attachments: </th>
				<td> {% for files in ticket.attachments %} List attachment  {% endfor %}</td>	 

			</tr>


		</table>
		<br />
		<h4>Description:</h4> <br> {{ ticket.body }}
	</div>
</div>

{% endmacro %}


{%- macro comment_span12_tile(comment_array) -%}
{% for row in comment_array %}
<div class="row">
	{% for content in row %}
	<div class="span12">
		{{comment.username}}            <br> <br>		{{ comment.body }}
	</div>
	{% endfor %}
</div>
{% endfor %}
{% endmacro %}

semaphore/semaphore/templates/dashboard/ticket_view.html
{% extends 'dashboard/dashboard_base.html' %}
{% import 'tickets/ticket_tiles.html' as tickets %}
{% block title %}{{ g.organization.name }} - Viewing Ticket{% endblock %}
{% block dash_content %}
    <h2>{{ ticket.title }}</h2> <!-- Keep for testing-->
    {{ tickets.span8_ticketlist(ticket_array) }} <!--shows the recent ticket list if passed in an array. Needs to be filtered though -->
{% endblock %}

semaphore/semaphore/templates/dashboard/tiles.html
{%- macro span8_tile(content_array) -%}
{% for row in content_array %}
<div class="row">
{% for content in row %}
 <div class="span8">
                    <div class ="well">
                   		{{ content }}
                    </div>
                 </div>
{% endfor %}
</div>
{% endfor %}
{% endmacro %}